spring.application.name=demo app

spring.datasource.url=jdbc:postgresql://localhost:5432/Postgres
atasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
